"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Json_1 = require("./Json");
var List_1 = require("./List");
console.log("Test Sort");
console.log("######################################################");
List_1.List.testSort();
console.log("######################################################");
console.log("\nTest Buggy Sort");
console.log("######################################################");
List_1.List.testBuggySort();
console.log("######################################################");
console.log("\nTest Dummy Sort");
console.log("######################################################");
List_1.List.testDummySort();
console.log("######################################################");
console.log("\n\nTest JSON Stringify");
console.log("######################################################");
Json_1.Json.testJsonStringify();
console.log("######################################################");
console.log("\nTest Custom JSON Stringify");
console.log("######################################################");
Json_1.Json.testJsonMyStringify();
console.log("######################################################");
